-- نظام تيبان: شغّلي هذا الملف كاملًا في Supabase SQL Editor
create type public.user_role as enum ('admin', 'teacher', 'student');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.user_role not null default 'student',
  teacher_id uuid references public.profiles(id) on delete set null,
  student_code text unique,
  phone text,
  created_at timestamptz not null default now()
);

create table public.student_records (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  new_memorization text,
  review text,
  evaluation text,
  homework text,
  next_lesson text,
  notes text,
  attendance text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  details text,
  due_date text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table public.payments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  amount numeric(10,2),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.is_teacher_of(target uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = target and teacher_id = auth.uid()); $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'طالبة جديدة'), 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.student_records enable row level security;
alter table public.assignments enable row level security;
alter table public.payments enable row level security;

create policy "profile owner or admin" on public.profiles for select using (id = auth.uid() or teacher_id = auth.uid() or public.is_admin());
create policy "admin manages profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());
create policy "student or teacher records" on public.student_records for select using (student_id = auth.uid() or teacher_id = auth.uid() or public.is_admin());
create policy "teacher creates records" on public.student_records for insert with check (teacher_id = auth.uid() and public.is_teacher_of(student_id));
create policy "teacher updates records" on public.student_records for update using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());
create policy "student assignments" on public.assignments for select using (student_id = auth.uid() or teacher_id = auth.uid() or public.is_admin());
create policy "teacher manages assignments" on public.assignments for all using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());
create policy "student payments" on public.payments for select using (student_id = auth.uid() or teacher_id = auth.uid() or public.is_admin());
create policy "teacher manages payments" on public.payments for all using (teacher_id = auth.uid()) with check (teacher_id = auth.uid());

create table if not exists public.teacher_backups (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.teacher_backups enable row level security;

drop policy if exists "teacher reads own backup" on public.teacher_backups;
create policy "teacher reads own backup" on public.teacher_backups
  for select using (user_id = auth.uid());

drop policy if exists "teacher creates own backup" on public.teacher_backups;
create policy "teacher creates own backup" on public.teacher_backups
  for insert with check (user_id = auth.uid());

drop policy if exists "teacher updates own backup" on public.teacher_backups;
create policy "teacher updates own backup" on public.teacher_backups
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "teacher deletes own backup" on public.teacher_backups;
create policy "teacher deletes own backup" on public.teacher_backups
  for delete using (user_id = auth.uid());
