-- Run this script in Supabase SQL Editor.
create type public.user_role as enum ('admin', 'teacher', 'student');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.user_role not null default 'student',
  created_at timestamptz not null default now()
);

create table public.teacher_students (
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  student_code text not null unique,
  primary key (teacher_id, student_id)
);

create table public.student_records (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  new_memorization text,
  review text,
  evaluation text,
  homework text,
  next_lesson text,
  notes text,
  attendance text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.payments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(10,2) not null,
  payment_method text not null default 'Touch ''n Go eWallet',
  payment_status text not null default 'pending',
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

-- Creates a private student profile automatically after student registration.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'طالبة جديدة'), 'student')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.teacher_students enable row level security;
alter table public.student_records enable row level security;
alter table public.payments enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.is_teacher_of(target_student uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.teacher_students where teacher_id = auth.uid() and student_id = target_student); $$;

create policy "users read their own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "admins manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

create policy "linked users read relationships" on public.teacher_students for select using (teacher_id = auth.uid() or student_id = auth.uid() or public.is_admin());
create policy "admins manage relationships" on public.teacher_students for all using (public.is_admin()) with check (public.is_admin());

create policy "students read their records" on public.student_records for select using (student_id = auth.uid() or teacher_id = auth.uid() or public.is_admin());
create policy "teachers create records for their students" on public.student_records for insert with check (teacher_id = auth.uid() and public.is_teacher_of(student_id));
create policy "teachers update their students records" on public.student_records for update using (teacher_id = auth.uid() and public.is_teacher_of(student_id)) with check (teacher_id = auth.uid() and public.is_teacher_of(student_id));

create policy "students read their payments" on public.payments for select using (student_id = auth.uid() or public.is_admin());
create policy "admins manage payments" on public.payments for all using (public.is_admin()) with check (public.is_admin());